language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"
before_script:
  - npm install -g gulp
script: gulp test
deploy:
	provider: npm
	email: $EMAIL
	api_key: $NPM_API_KEY
	on:
 		tags: true